### ISSUE TITLE
zef install Spreadsheet::XLXS fails due to missing files

### ISSUE THREAD

**Issue by NBEng** [jnthn/spreadsheet-xlsx#11]
This is a Raku newbie question and probably has an easy answer, but I haven't been able to figure it out,

Yesterday, I installed the Rakudo Star Bundle on Debian Linux 10 (installed it in a personal subdirectory ~/rakudo)

zef was able to find Spreadsheet::XLXS as can be seen from the following output:

```
nick@patsan10:~/Perl/raku$ zef info Spreadsheet::XLSX
- Info for: Spreadsheet::XLSX
- Identity: Spreadsheet::XLSX:ver<0.2.2>:auth<Edument>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: No
Description:	 Work with Excel (XLSX) spreadsheets.
License:	 Artistic-2.0
Source-url:	 https://github.com/jnthn/spreadsheet-xlsx.git
Provides: 11 modules
Depends: 2 items

```
However, when I tried to install it, the following resulted:

```
nick@patsan10:~/Perl/raku$ zef install Spreadsheet::XLSX
===> Searching for: Spreadsheet::XLSX
===> Searching for missing dependencies: LibXML:ver<0.5.10+>
===> Searching for missing dependencies: Method::Also
===> Building: LibXML:ver<0.5.14>:auth<cpan:WARRINGD>
[LibXML] In file included from src/dom.c:10:
[LibXML] src/dom.h:17:10: fatal error: libxml/tree.h: No such file or directory
[LibXML]  #include <libxml/tree.h>
[LibXML]           ^~~~~~~~~~~~~~~
[LibXML] compilation terminated.
[LibXML] make: *** [Makefile:24: src/dom.o] Error 1
[LibXML] The spawned command 'make' exited unsuccessfully (exit code: 2, signal: 0)
[LibXML]   in method build at /home/nick/.zef/store/LibXML-0.5.14.tar.gz/LibXML-0.5.14/Build.pm line 33
[LibXML]   in sub MAIN at /home/nick/.zef/store/LibXML-0.5.14.tar.gz/LibXML-0.5.14/Build.pm line 40
[LibXML]   in block <unit> at /home/nick/.zef/store/LibXML-0.5.14.tar.gz/LibXML-0.5.14/Build.pm line 5
[LibXML]   in block <unit> at -e line 1
===> Building [FAIL]: LibXML:ver<0.5.14>:auth<cpan:WARRINGD>
Aborting due to build failure: LibXML:ver<0.5.14>:auth<cpan:WARRINGD> (use --force-build to override)
```

A recursive search through the ~/rakudo directory tree in the  didn't find the file dom.h  As I'm newbie with both raku and the use of zef, I'd appreciate some advice on how I can solve this problem.... OK, I found this file is a subdirectory or ~/.zef 
So, it looks like zef is not able to use it there for some reason?

Thanks!

Nick

**Comment by jnthn** [comment]
Looks like it's because the installation of a dependency of this module fails:

> ===> Building [FAIL]: LibXML:ver<0.5.14>:auth<cpan:WARRINGD>

I expect the error a little above it occurs because that depends on the libxml library being installed. There are some [instructions on how to do that for some platforms here](https://github.com/libxml-raku/LibXML-raku#prerequisites).

**Comment by NBEng** [comment]
From the link you provided, I discovered that I needed to install a missing library.  After I did the following:

`apt-get install libxml2-dev`

LibXML installed properly -  and after that, so did Spreadsheet:XLXS

Thank you so much!
